# -*-Makefile-*-

# (Re)compile and run
run ARG1='' ARG2='':
	#!/usr/bin/env sh
	cmake -S . -B build &&
	cmake --build build -j &&
	build/double-sipm {{ARG1}} {{ARG2}}

# Remove all traces of the local copy of the example
clean:
	rm build -rf
